### ISSUE TITLE
seg fault on Read()

### ISSUE THREAD

**Issue by K6TD** [stianeikeland/go-rpio#90]
Error on fsPin.Read()

unexpected fault address 0x7f8034e034
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f8034e034 pc=0x2b0abc]

err :-rpio.Open() (err ==nil)
fsPin.Input()
fsPin = rpio.Pin(10)

$ ll /dev/gpiomem
crw-rw---- 1 root gpio 245, 0 Aug 27 23:38 /dev/gpiomem
groups kevin
kevin : kevin adm dialout cdrom sudo audio video plugdev games users input render gpionetdev spi i2c lpadmin
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

Tried other OS'es.  Same error.

**Comment by K6TD** [comment]
And:
go version go1.21.0 linux/arm64

**Comment by Aterocana** [comment]
I confirm: I have the same issue:
```
unexpected fault address 0xae8ac000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xae8ac000 pc=0xb15a4]

goroutine 1 [running]:
runtime.throw({0xd40eb, 0x5})
        /usr/lib/go/src/runtime/panic.go:1077 +0x4c fp=0x10b7edc sp=0x10b7ec8 pc=0x48bd4
runtime.sigpanic()
        /usr/lib/go/src/runtime/signal_unix.go:875 +0x2c0 fp=0x10b7f0c sp=0x10b7edc pc=0x60ed0
github.com/stianeikeland/go-rpio/v4.PinMode(0x4, 0x1)
        .../vendor/github.com/stianeikeland/go-rpio/v4/rpio.go:378 +0x24c fp=0x10b7f34 sp=0x10b7f10 pc=0
xb15a4
github.com/stianeikeland/go-rpio/v4.Pin.Output(...)
        .../github.com/stianeikeland/go-rpio/v4/rpio.go:193
```
